2022-02-17 13:33:18 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration average which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-17 13:33:18 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-17 13:33:18 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration powercalc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-17 13:33:18 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-17 13:33:18 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration audiconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-17 13:33:18 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration adaptive_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-17 13:33:18 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration monitor_docker which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-17 13:33:18 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miio_fan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-17 13:33:18 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration shelly which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-17 13:33:18 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-17 13:33:18 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration thermal_comfort which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-17 13:33:18 WARNING (SyncWorker_7) [homeassistant.loader] We found a custom integration tuya_v2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-17 13:33:18 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration tgtg which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-17 13:33:18 WARNING (SyncWorker_9) [homeassistant.loader] We found a custom integration googlewifi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-17 13:33:18 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration huesyncbox which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-17 13:33:18 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration afvalbeheer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-17 13:33:18 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration anniversaries which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-17 13:33:18 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration buienalarm which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-17 13:33:18 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-17 13:33:18 WARNING (SyncWorker_8) [homeassistant.loader] We found a custom integration frigate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-17 13:33:18 WARNING (SyncWorker_10) [homeassistant.loader] We found a custom integration deepstack_face which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-17 13:33:18 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration google_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-17 13:33:18 WARNING (SyncWorker_7) [homeassistant.loader] We found a custom integration ytube_music_player which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-17 13:33:28 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: template value should be a string for dictionary value @ data['action'][0]['data']. Got None. (See ?, line ?). 
2022-02-17 13:33:29 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: template value should be a string for dictionary value @ data['action'][0]['data']. Got None. (See ?, line ?). 
2022-02-17 13:33:33 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 5fc6e46f1fd47b1a3e7ad935efdabc15f9dc421ed850271abc891db73beb0aa4 from 185.194.187.56
2022-02-17 13:33:47 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 5fc6e46f1fd47b1a3e7ad935efdabc15f9dc421ed850271abc891db73beb0aa4 from 185.194.187.56
2022-02-17 13:33:48 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281473111210976] Received invalid command: mobile_app/push_notification_channel
2022-02-17 13:33:49 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 9ad6a9a388f054ed2b5f4c5982f506c386b38e900fcec728eb6a0df2f98bac6c from 192.168.86.40
2022-02-17 13:33:58 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 9ad6a9a388f054ed2b5f4c5982f506c386b38e900fcec728eb6a0df2f98bac6c from 192.168.86.40
2022-02-17 13:33:58 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 9ad6a9a388f054ed2b5f4c5982f506c386b38e900fcec728eb6a0df2f98bac6c from 192.168.86.40
2022-02-17 13:33:59 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 9ad6a9a388f054ed2b5f4c5982f506c386b38e900fcec728eb6a0df2f98bac6c from 192.168.86.40
2022-02-17 13:34:27 WARNING (MainThread) [homeassistant.config_entries] Config entry 'GoogleTV' for nfandroidtv integration not ready yet: Failed to connect; Retrying in background
2022-02-17 13:34:31 WARNING (MainThread) [homeassistant.components.fan] Platform xiaomi_miio_fan not ready yet: Unable to discover the device 192.168.86.28; Retrying in background in 30 seconds
2022-02-17 13:34:31 WARNING (MainThread) [homeassistant.components.fan] Platform xiaomi_miio_fan not ready yet: Unable to discover the device 192.168.86.29; Retrying in background in 30 seconds
2022-02-17 13:34:32 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call inside the event loop. This is causing stability issues. Please report issue for google_cloud doing blocking calls at homeassistant/components/google_cloud/tts.py, line 212: self._client = texttospeech.TextToSpeechClient()
2022-02-17 13:34:32 ERROR (MainThread) [homeassistant.components.tts] Error setting up platform: google_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 163, in async_setup_platform
    provider = await platform.async_get_engine(
  File "/usr/src/homeassistant/homeassistant/components/google_cloud/tts.py", line 162, in async_get_engine
    return GoogleCloudTTSProvider(
  File "/usr/src/homeassistant/homeassistant/components/google_cloud/tts.py", line 212, in __init__
    self._client = texttospeech.TextToSpeechClient()
  File "/usr/local/lib/python3.9/site-packages/google/cloud/texttospeech_v1/gapic/text_to_speech_client.py", line 141, in __init__
    self.transport = text_to_speech_grpc_transport.TextToSpeechGrpcTransport(
  File "/usr/local/lib/python3.9/site-packages/google/cloud/texttospeech_v1/gapic/transports/text_to_speech_grpc_transport.py", line 60, in __init__
    channel = self.create_channel(address=address, credentials=credentials)
  File "/usr/local/lib/python3.9/site-packages/google/cloud/texttospeech_v1/gapic/transports/text_to_speech_grpc_transport.py", line 87, in create_channel
    return google.api_core.grpc_helpers.create_channel(
  File "/usr/local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 302, in create_channel
    composite_credentials = _create_composite_credentials(
  File "/usr/local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 236, in _create_composite_credentials
    credentials, _ = google.auth.default(
  File "/usr/local/lib/python3.9/site-packages/google/auth/_default.py", line 544, in default
    credentials, project_id = checker()
  File "/usr/local/lib/python3.9/site-packages/google/auth/_default.py", line 540, in <lambda>
    lambda: _get_gce_credentials(request),
  File "/usr/local/lib/python3.9/site-packages/google/auth/_default.py", line 274, in _get_gce_credentials
    if _metadata.ping(request=request):
  File "/usr/local/lib/python3.9/site-packages/google/auth/compute_engine/_metadata.py", line 85, in ping
    response = request(
  File "/usr/local/lib/python3.9/site-packages/google/auth/transport/_http_client.py", line 106, in __call__
    connection.request(method, path, body=body, headers=headers, **kwargs)
  File "/usr/local/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1290, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 166, in protected_loop_func
    check_loop(func, strict=strict)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 154, in check_loop
    raise RuntimeError(
RuntimeError: Blocking calls must be done in the executor or a separate thread; Use `await hass.async_add_executor_job()` at homeassistant/components/google_cloud/tts.py, line 212: self._client = texttospeech.TextToSpeechClient()
2022-02-17 13:34:33 WARNING (MainThread) [homeassistant.components.fan] Setup of fan platform xiaomi_miio_airpurifier is taking over 10 seconds.
2022-02-17 13:34:33 WARNING (MainThread) [homeassistant.config_entries] Config entry '192.168.86.83' for synology_dsm integration not ready yet: ConnectionError = <urllib3.connection.HTTPSConnection object at 0xffff8b68d6d0>: Failed to establish a new connection: [Errno 113] Host is unreachable; Retrying in background
2022-02-17 13:34:39 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of binary_sensor platform pi_hole is taking over 10 seconds.
2022-02-17 13:34:40 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Hueland 2' for hue integration not ready yet: Error connecting to the Hue bridge at 192.168.86.84; Retrying in background
2022-02-17 13:34:40 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Hueland 1' for hue integration not ready yet: Error connecting to the Hue bridge at 192.168.86.39; Retrying in background
2022-02-17 13:34:41 WARNING (MainThread) [homeassistant.components.light] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2022-02-17 13:34:41 WARNING (MainThread) [homeassistant.components.select] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.outside_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.outside_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.outside_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.outside_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.living_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.living_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.living_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.living_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.kamer_amilya_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.kamer_amilya_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.kamer_amilya_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.kamer_amilya_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.veranda_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.veranda_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.veranda_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.veranda_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.berging_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.berging_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.berging_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.berging_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.gang_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.gang_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.gang_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.gang_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.badkamer_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.badkamer_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.badkamer_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.badkamer_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.kamer_alunya_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.kamer_alunya_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.kamer_alunya_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.kamer_alunya_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.master_bedroom_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.master_bedroom_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.master_bedroom_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:42 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.master_bedroom_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-17 13:34:44 ERROR (MainThread) [custom_components.powercalc.model_discovery] light.amilya_plafond: Cannot autodiscover model, manufacturer or model unknown from device registry
2022-02-17 13:34:44 ERROR (MainThread) [custom_components.powercalc.sensors.power] Skipping sensor setup light.amilya_plafond: Cannot select a mode (LINEAR, FIXED or LUT, WLED), supply it in the config
2022-02-17 13:34:44 ERROR (MainThread) [custom_components.powercalc.model_discovery] light.amilya_staande_lamp: Cannot autodiscover model, manufacturer or model unknown from device registry
2022-02-17 13:34:44 ERROR (MainThread) [custom_components.powercalc.sensors.power] Skipping sensor setup light.amilya_staande_lamp: Cannot select a mode (LINEAR, FIXED or LUT, WLED), supply it in the config
2022-02-17 13:34:44 ERROR (MainThread) [custom_components.powercalc.sensors.power] Skipping sensor setup light.buiten: ('No lookup file found for mode', 'brightness')
2022-02-17 13:34:46 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: googlewifi, google_home, upnp, camera.netatmo, climate.netatmo, sensor.command_line, sensor.command_line_2, sensor.thermal_comfort, sensor.template, sensor.history_stats, sensor.afvalbeheer, sensor.buienalarm, sensor.time_date, sensor.min_max, sensor.scrape, sensor.scrape_2, sensor.scrape_3, sensor.scrape_4, sensor.scrape_5, sensor.scrape_6, sensor.scrape_7, sensor.systemmonitor, sensor.command_line_3, sensor.integration, sensor.filesize, sensor.buienradar, sensor.speedtestdotnet, sensor.pi_hole, sensor.hacs, sensor.openweathermap, sensor.co2signal, sensor.plex, sensor.mobile_app, sensor.mobile_app_2, sensor.mobile_app_3, sensor.mobile_app_4, sensor.mobile_app_5, sensor.tado, sensor.tuya, sensor.brother, sensor.deconz, sensor.ipp, sensor.netatmo, sensor.powercalc, sensor.anniversaries, sensor.energy, sensor.utility_meter, default_config, sensor.powercalc_13, sensor.powercalc_14, sensor.powercalc_15, sensor.powercalc_16, sensor.powercalc_17, sensor.powercalc_18, sensor.powercalc_19, sensor.powercalc_20, sensor.powercalc_21, sensor.powercalc_22, sensor.powercalc_23, sensor.powercalc_24, sensor.powercalc_25, sensor.powercalc_26, sensor.powercalc_27, sensor.powercalc_28, sensor.powercalc_29, sensor.powercalc_30, sensor.powercalc_31, sensor.powercalc_32, sensor.powercalc_33, sensor.powercalc_34, sensor.powercalc_35, sensor.powercalc_36, sensor.powercalc_37, sensor.powercalc_38, sensor.powercalc_39, sensor.powercalc_40, sensor.powercalc_41, media_player.huesyncbox
2022-02-17 13:34:47 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-17 13:34:47 WARNING (MainThread) [homeassistant.components.integration.sensor] Could not restore last state: [<class 'decimal.ConversionSyntax'>]
2022-02-17 13:34:47 WARNING (MainThread) [homeassistant.components.integration.sensor] Could not restore last state: [<class 'decimal.ConversionSyntax'>]
2022-02-17 13:34:47 WARNING (MainThread) [homeassistant.components.integration.sensor] Could not restore last state: [<class 'decimal.ConversionSyntax'>]
2022-02-17 13:34:48 WARNING (MainThread) [homeassistant.config_entries] Config entry 'OnHub' for upnp integration not ready yet; Retrying in background
2022-02-17 13:34:48 WARNING (MainThread) [homeassistant.components.climate] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2022-02-17 13:34:48 WARNING (MainThread) [homeassistant.components.camera] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2022-02-17 13:34:49 WARNING (MainThread) [homeassistant.components.sensor] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2022-02-17 13:34:51 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2022-02-17 13:34:51 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2022-02-17 13:34:51 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2022-02-17 13:34:51 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2022-02-17 13:34:51 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2022-02-17 13:34:51 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2022-02-17 13:34:51 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.google_server is taking over 10 seconds
2022-02-17 13:34:51 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-17 13:34:58 ERROR (MainThread) [homeassistant.components.sensor] scrape: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 718, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 186, in async_update
    await self._async_update_from_rest_data()
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 199, in _async_update_from_rest_data
    value = await self.hass.async_add_executor_job(self._extract_value)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 167, in _extract_value
    tag = raw_data.select(self._select)[self._index]
  File "/usr/local/lib/python3.9/site-packages/bs4/element.py", line 1949, in select
    results = soupsieve.select(selector, self, namespaces, limit, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/__init__.py", line 144, in select
    return compile(select, namespaces, flags, **kwargs).select(tag, limit)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/__init__.py", line 67, in compile
    return cp._cached_css_compile(pattern, ns, cs, flags)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 218, in _cached_css_compile
    CSSParser(
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 1159, in process_selectors
    return self.parse_selectors(self.selector_iter(self.pattern), index, flags)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 985, in parse_selectors
    key, m = next(iselector)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 1152, in selector_iter
    raise SelectorSyntaxError(msg, self.pattern, index)
soupsieve.util.SelectorSyntaxError: Invalid character '<' position 0
  line 1:
<span _ngcontent-app-root-c173="">Offline</span>
^
2022-02-17 13:35:06 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{{ (10 * states('sensor.audi_e_tron_sportback_55_primary_engine_range') | float(default=0) / states('sensor.audi_e_tron_sportback_55_state_of_charge') | float(default=0) ) | round (1) }}")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 407, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1814, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
ZeroDivisionError: division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 523, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 409, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ZeroDivisionError: division by zero
2022-02-17 13:35:06 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ZeroDivisionError: division by zero') while processing template 'Template("{{ (10 * states('sensor.audi_e_tron_sportback_55_primary_engine_range') | float(default=0) / states('sensor.audi_e_tron_sportback_55_state_of_charge') | float(default=0) ) | round (1) }}")' for attribute '_attr_native_value' in entity 'sensor.car_range_per_10percent'
2022-02-17 13:35:12 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2022-02-17 13:35:18 ERROR (Recorder) [homeassistant] Error doing job: Unclosed client session
2022-02-17 13:35:18 ERROR (Recorder) [homeassistant] Error doing job: Unclosed client session
2022-02-17 13:35:30 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/netatmo/__init__.py", line 233, in register_webhook
    await hass.data[DOMAIN][entry.entry_id][AUTH].async_addwebhook(webhook_url)
  File "/usr/local/lib/python3.9/site-packages/pyatmo/auth.py", line 377, in async_addwebhook
    resp = await self.async_post_request(WEBHOOK_URL_ADD, {"url": webhook_url})
  File "/usr/local/lib/python3.9/site-packages/pyatmo/auth.py", line 335, in async_post_request
    async with self.websession.post(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 634, in _request
    break
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
2022-02-17 13:35:30 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-17 13:35:31 WARNING (MainThread) [homeassistant.components.fan] Setup of fan platform xiaomi_miio_fan is taking over 10 seconds.
2022-02-17 13:35:31 WARNING (MainThread) [homeassistant.components.fan] Setup of fan platform xiaomi_miio_fan is taking over 10 seconds.
2022-02-17 13:35:35 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.google_server is taking over 10 seconds
2022-02-17 13:35:35 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2022-02-17 13:35:35 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-17 13:35:35 WARNING (MainThread) [homeassistant.components.media_player] Updating samsungtv media_player took longer than the scheduled update interval 0:00:10
2022-02-17 13:35:35 WARNING (MainThread) [homeassistant.components.media_player] Updating dlna_dmr media_player took longer than the scheduled update interval 0:00:10
2022-02-17 13:35:35 ERROR (MainThread) [homeassistant.components.mobile_app.notify] Timeout sending notification to https://mobile-apps.home-assistant.io/api/sendPush/android/v1
2022-02-17 13:35:35 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2022-02-17 13:35:36 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-17 13:35:41 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2022-02-17 13:35:41 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-17 13:35:44 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2022-02-17 13:35:45 ERROR (MainThread) [homeassistant.components.hue.bridge] Unknown error connecting to Hue bridge
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hue/bridge.py", line 75, in async_initialize_bridge
    await self.api.initialize()
  File "/usr/local/lib/python3.9/site-packages/aiohue/v2/__init__.py", line 103, in initialize
    await self.fetch_full_state()
  File "/usr/local/lib/python3.9/site-packages/aiohue/v2/__init__.py", line 241, in fetch_full_state
    await asyncio.gather(
  File "/usr/local/lib/python3.9/site-packages/aiohue/v2/controllers/base.py", line 306, in initialize
    await resource_control.initialize(initial_data)
  File "/usr/local/lib/python3.9/site-packages/aiohue/v2/controllers/base.py", line 80, in initialize
    resource: CLIPResource = dataclass_from_dict(self.item_cls, item)
  File "/usr/local/lib/python3.9/site-packages/aiohue/util.py", line 206, in dataclass_from_dict
    **{
  File "/usr/local/lib/python3.9/site-packages/aiohue/util.py", line 207, in <dictcomp>
    field.name: _parse_value(
  File "/usr/local/lib/python3.9/site-packages/aiohue/util.py", line 144, in _parse_value
    return dataclass_from_dict(value_type, value)
  File "/usr/local/lib/python3.9/site-packages/aiohue/util.py", line 206, in dataclass_from_dict
    **{
  File "/usr/local/lib/python3.9/site-packages/aiohue/util.py", line 207, in <dictcomp>
    field.name: _parse_value(
  File "/usr/local/lib/python3.9/site-packages/aiohue/util.py", line 178, in _parse_value
    raise KeyError(f"`{name}` of type `{value_type}` is required.")
KeyError: "`MotionSensingFeature.motion` of type `<class 'bool'>` is required."
2022-02-17 13:35:51 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-17 13:36:01 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-17 13:37:03 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.veranda_speaker_aan_vandaag fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 725, in async_device_update
    raise exc
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 228, in async_update
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 234, in _update
    history_list = history.state_changes_during_period(
  File "/usr/src/homeassistant/homeassistant/components/recorder/history.py", line 143, in state_changes_during_period
    with session_scope(hass=hass) as session:
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 76, in session_scope
    session = hass.data[DATA_INSTANCE].get_session()
TypeError: 'NoneType' object is not callable
