2021-11-20 16:48:57 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration adaptive_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-20 16:48:57 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration average which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-20 16:48:57 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-20 16:48:57 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration audiconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-20 16:48:57 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration powercalc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-20 16:48:57 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration monitor_docker which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-20 16:48:57 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-20 16:48:57 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-20 16:48:57 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration xiaomi_miio_fan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-20 16:48:57 WARNING (SyncWorker_8) [homeassistant.loader] We found a custom integration huesyncbox which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-20 16:48:57 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration shelly which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-20 16:48:57 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration buienalarm which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-20 16:48:57 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration frigate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-20 16:48:57 WARNING (SyncWorker_7) [homeassistant.loader] We found a custom integration tuya_v2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-20 16:48:57 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration thermal_comfort which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-20 16:48:57 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration anniversaries which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-20 16:48:57 WARNING (SyncWorker_12) [homeassistant.loader] We found a custom integration afvalbeheer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-20 16:48:57 WARNING (SyncWorker_9) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-20 16:48:57 WARNING (SyncWorker_8) [homeassistant.loader] We found a custom integration ytube_music_player which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-20 16:48:57 WARNING (SyncWorker_10) [homeassistant.loader] We found a custom integration googlewifi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-20 16:48:57 WARNING (SyncWorker_11) [homeassistant.loader] We found a custom integration tgtg which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-20 16:48:57 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration google_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-20 16:48:57 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration deepstack_face which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-20 16:49:04 ERROR (SyncWorker_9) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0xffff89698190>: Failed to establish a new connection: [Errno 111] Connection refused'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2021-11-20 16:49:06 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: expected str for dictionary value @ data['from']. Got None. (See ?, line ?). 
2021-11-20 16:49:06 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['trigger'][1]['platform']. Got None. (See ?, line ?). 
2021-11-20 16:49:06 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: Unexpected value for condition: 'None'. Expected and, device, not, numeric_state, or, state, sun, template, time, trigger, zone @ data['condition'][0]. Got None. (See ?, line ?). 
2021-11-20 16:49:06 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: Unexpected value for condition: 'None'. Expected and, device, not, numeric_state, or, state, sun, template, time, trigger, zone @ data['condition'][0]. Got None. (See ?, line ?). 
2021-11-20 16:49:06 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['action'][4]['domain']. Got None. (See ?, line ?). 
2021-11-20 16:49:07 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-11-20 16:49:07 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-11-20 16:49:11 WARNING (MainThread) [homeassistant.setup] Setup of input_number is taking over 10 seconds.
2021-11-20 16:49:11 WARNING (MainThread) [homeassistant.setup] Setup of counter is taking over 10 seconds.
2021-11-20 16:49:12 WARNING (MainThread) [homeassistant.components.fan] Platform xiaomi_miio_fan not ready yet: Unable to discover the device 192.168.86.28; Retrying in background in 30 seconds
2021-11-20 16:49:12 WARNING (MainThread) [homeassistant.components.fan] Platform xiaomi_miio_fan not ready yet: Unable to discover the device 192.168.86.29; Retrying in background in 30 seconds
2021-11-20 16:49:12 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 8b8f82ade2e454d538c7b1b55e021814b7aa12b9fa3693773bc28dc044af0487 from 192.168.86.34
2021-11-20 16:49:12 WARNING (MainThread) [homeassistant.setup] Setup of input_select is taking over 10 seconds.
2021-11-20 16:49:12 WARNING (MainThread) [homeassistant.setup] Setup of input_datetime is taking over 10 seconds.
2021-11-20 16:49:12 WARNING (MainThread) [homeassistant.setup] Setup of zone is taking over 10 seconds.
2021-11-20 16:49:12 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 80adf825ef6b969ee3c95fc54091652f8a80fe790532f31c6bff63908742af08 from 192.168.86.26
2021-11-20 16:49:15 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 8b8f82ade2e454d538c7b1b55e021814b7aa12b9fa3693773bc28dc044af0487 from 192.168.86.34
2021-11-20 16:49:15 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 8b8f82ade2e454d538c7b1b55e021814b7aa12b9fa3693773bc28dc044af0487 from 192.168.86.34
2021-11-20 16:49:15 WARNING (MainThread) [homeassistant.config_entries] Config entry '192.168.86.83' for synology_dsm integration not ready yet: ConnectionError = <urllib3.connection.HTTPSConnection object at 0xffff7d5d9430>: Failed to establish a new connection: [Errno 113] Host is unreachable; Retrying in background
2021-11-20 16:49:18 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden'
2021-11-20 16:49:18 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden'
2021-11-20 16:49:18 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input '' when rendering template 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-20 16:49:18 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'timestamp_custom' got invalid input 'None' when rendering template 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden' but no default was specified. Currently 'timestamp_custom' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-20 16:49:18 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden'
2021-11-20 16:49:18 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden'
2021-11-20 16:49:18 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input '' when rendering template 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-20 16:49:18 WARNING (Thread-2) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering or compiling ''
2021-11-20 16:49:18 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden'
2021-11-20 16:49:18 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden'
2021-11-20 16:49:18 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input '' when rendering template 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-20 16:49:18 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'timestamp_custom' got invalid input 'None' when rendering template 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden' but no default was specified. Currently 'timestamp_custom' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-20 16:49:18 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden'
2021-11-20 16:49:18 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden'
2021-11-20 16:49:18 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input '' when rendering template 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-20 16:49:18 WARNING (Thread-2) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering or compiling ''
2021-11-20 16:49:18 WARNING (Thread-2) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering or compiling ''
2021-11-20 16:49:18 WARNING (Thread-2) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering or compiling ''
2021-11-20 16:49:20 WARNING (MainThread) [homeassistant.components.light] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2021-11-20 16:49:20 WARNING (MainThread) [homeassistant.components.select] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2021-11-20 16:49:22 WARNING (MainThread) [homeassistant.components.integration.sensor] Could not restore last state: [<class 'decimal.ConversionSyntax'>]
2021-11-20 16:49:24 ERROR (MainThread) [custom_components.powercalc.sensors.power] Skipping sensor setup light.buiten: ('No lookup file found for mode', 'brightness')
2021-11-20 16:49:24 WARNING (MainThread) [homeassistant.components.energy.sensor] Found unexpected state_class None for sensor.tv_energy
2021-11-20 16:49:24 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Timeout fetching sensor data
2021-11-20 16:49:24 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Timeout fetching sensor data
2021-11-20 16:49:24 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-20 16:49:24 WARNING (MainThread) [homeassistant.components.climate] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2021-11-20 16:49:24 WARNING (MainThread) [homeassistant.components.camera] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2021-11-20 16:49:25 WARNING (MainThread) [homeassistant.components.sensor] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2021-11-20 16:49:25 WARNING (MainThread) [homeassistant.config_entries] Config entry 'OnHub' for upnp integration not ready yet; Retrying in background
2021-11-20 16:49:26 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform dlna_dmr is taking over 10 seconds.
2021-11-20 16:49:27 ERROR (MainThread) [homeassistant.components.sensor] scrape: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 651, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 166, in async_update
    await self._async_update_from_rest_data()
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 179, in _async_update_from_rest_data
    value = await self.hass.async_add_executor_job(self._extract_value)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 155, in _extract_value
    tag = raw_data.select(self._select)[self._index]
  File "/usr/local/lib/python3.9/site-packages/bs4/element.py", line 1949, in select
    results = soupsieve.select(selector, self, namespaces, limit, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/__init__.py", line 144, in select
    return compile(select, namespaces, flags, **kwargs).select(tag, limit)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/__init__.py", line 67, in compile
    return cp._cached_css_compile(pattern, ns, cs, flags)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 218, in _cached_css_compile
    CSSParser(
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 1159, in process_selectors
    return self.parse_selectors(self.selector_iter(self.pattern), index, flags)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 985, in parse_selectors
    key, m = next(iselector)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 1152, in selector_iter
    raise SelectorSyntaxError(msg, self.pattern, index)
soupsieve.util.SelectorSyntaxError: Invalid character '<' position 0
  line 1:
<span _ngcontent-app-root-c173="">Offline</span>
^
2021-11-20 16:49:29 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2021-11-20 16:49:29 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2021-11-20 16:49:29 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2021-11-20 16:49:29 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2021-11-20 16:49:29 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2021-11-20 16:49:30 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-20 16:49:30 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.google_server is taking over 10 seconds
2021-11-20 16:49:42 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2021-11-20 16:49:48 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-20 16:49:59 ERROR (MainThread) [homeassistant.components.mobile_app.notify] Timeout sending notification to https://mobile-apps.home-assistant.io/api/sendPush/android/v1
2021-11-20 16:50:00 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.google_server is taking over 10 seconds
2021-11-20 16:50:00 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-20 16:50:00 ERROR (MainThread) [homeassistant.components.hue.light] Timeout fetching light data
2021-11-20 16:50:01 ERROR (MainThread) [homeassistant.components.google_assistant.http] Could not contact https://homegraph.googleapis.com/v1/devices:requestSync
2021-11-20 16:50:01 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2021-11-20 16:50:05 ERROR (SyncWorker_9) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0xffff6e91b280>: Failed to establish a new connection: [Errno 111] Connection refused'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2021-11-20 16:50:07 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-11-20 16:50:42 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: expected str for dictionary value @ data['from']. Got None. (See ?, line ?). 
2021-11-20 16:50:42 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['trigger'][1]['platform']. Got None. (See ?, line ?). 
2021-11-20 16:50:42 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: Unexpected value for condition: 'None'. Expected and, device, not, numeric_state, or, state, sun, template, time, trigger, zone @ data['condition'][0]. Got None. (See ?, line ?). 
2021-11-20 16:50:42 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: Unexpected value for condition: 'None'. Expected and, device, not, numeric_state, or, state, sun, template, time, trigger, zone @ data['condition'][0]. Got None. (See ?, line ?). 
2021-11-20 16:50:42 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['action'][4]['domain']. Got None. (See ?, line ?). 
2021-11-20 16:50:42 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-11-20 16:50:42 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-11-20 16:51:05 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: expected str for dictionary value @ data['from']. Got None. (See ?, line ?). 
2021-11-20 16:51:05 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['trigger'][1]['platform']. Got None. (See ?, line ?). 
2021-11-20 16:51:05 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: Unexpected value for condition: 'None'. Expected and, device, not, numeric_state, or, state, sun, template, time, trigger, zone @ data['condition'][0]. Got None. (See ?, line ?). 
2021-11-20 16:51:05 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: Unexpected value for condition: 'None'. Expected and, device, not, numeric_state, or, state, sun, template, time, trigger, zone @ data['condition'][0]. Got None. (See ?, line ?). 
2021-11-20 16:51:05 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['action'][4]['domain']. Got None. (See ?, line ?). 
2021-11-20 16:51:05 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-11-20 16:51:05 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-11-20 16:51:05 ERROR (SyncWorker_17) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0xffff5bc29ee0>: Failed to establish a new connection: [Errno 111] Connection refused'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2021-11-20 16:51:05 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.veranda_speaker_aan_vandaag fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 468, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 658, in async_device_update
    raise exc
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 221, in async_update
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 227, in _update
    history_list = history.state_changes_during_period(
  File "/usr/src/homeassistant/homeassistant/components/recorder/history.py", line 147, in state_changes_during_period
    with session_scope(hass=hass) as session:
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 73, in session_scope
    session = hass.data[DATA_INSTANCE].get_session()
TypeError: 'NoneType' object is not callable
2021-11-20 16:51:05 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.master_bedroom_tv_aan_vandaag fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 468, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 658, in async_device_update
    raise exc
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 221, in async_update
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 227, in _update
    history_list = history.state_changes_during_period(
  File "/usr/src/homeassistant/homeassistant/components/recorder/history.py", line 147, in state_changes_during_period
    with session_scope(hass=hass) as session:
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 73, in session_scope
    session = hass.data[DATA_INSTANCE].get_session()
TypeError: 'NoneType' object is not callable
